/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../app/login/login.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../../app/user/user.service';
import * as import9 from '../../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import10 from '../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import11 from '../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import12 from '@angular/core/src/change_detection/change_detection_util';
import * as import13 from '@angular/core/src/linker/element_ref';
import * as import14 from '@angular/forms/src/directives/default_value_accessor';
import * as import15 from '@angular/forms/src/directives/control_value_accessor';
import * as import16 from '@angular/forms/src/directives/ng_model';
import * as import17 from '@angular/forms/src/directives/ng_control';
import * as import18 from '@angular/forms/src/directives/ng_control_status';
export class Wrapper_LoginComponent {
  /*private*/ _eventHandler:Function;
  context:import0.LoginComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any) {
    this._changed = false;
    this.context = new import0.LoginComponent(p0);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_LoginComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_LoginComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.LoginComponent>;
  _LoginComponent_0_3:Wrapper_LoginComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_LoginComponent_Host0,renderType_LoginComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'ng-component',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_LoginComponent0(this.viewUtils,this,0,this._el_0);
    this._LoginComponent_0_3 = new Wrapper_LoginComponent(this.injectorGet(import8.UserService,this.parentIndex));
    this.compView_0.create(this._LoginComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._LoginComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.LoginComponent) && (0 === requestNodeIndex))) { return this._LoginComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._LoginComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const LoginComponentNgFactory:import7.ComponentFactory<import0.LoginComponent> = new import7.ComponentFactory<import0.LoginComponent>('ng-component',View_LoginComponent_Host0,import0.LoginComponent);
const styles_LoginComponent:any[] = ([] as any[]);
var renderType_LoginComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_LoginComponent,{});
export class View_LoginComponent0 extends import1.AppView<import0.LoginComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _text_37:any;
  _el_38:any;
  _DefaultValueAccessor_38_3:import9.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_38_4:any[];
  _NgModel_38_5:import10.Wrapper_NgModel;
  _NgControl_38_6:any;
  _NgControlStatus_38_7:import11.Wrapper_NgControlStatus;
  _text_39:any;
  _el_40:any;
  _text_41:any;
  _el_42:any;
  _text_43:any;
  _text_44:any;
  _text_45:any;
  _text_46:any;
  _text_47:any;
  _text_48:any;
  _text_49:any;
  _text_50:any;
  _text_51:any;
  /*private*/ _expr_57:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_LoginComponent0,renderType_LoginComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._expr_57 = import12.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','login-component-container vertical-center'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','container'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'div',new import3.InlineArray2(2,'class','col-md-12 col-xs-12 col-lg-12'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_6,'div',new import3.InlineArray2(2,'style','justify-content: center; display: flex; align-items: center; margin-top: 10%;'),(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'\n                ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_8,'img',new import3.InlineArray4(4,'class','logo','src','assets/images/marker_walkable.svg'),(null as any));
    this._text_11 = this.renderer.createText(this._el_8,'\n                ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_8,'img',new import3.InlineArray4(4,'class','logo','src','assets/images/marker_border.svg'),(null as any));
    this._text_13 = this.renderer.createText(this._el_8,'\n                ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_8,'img',new import3.InlineArray4(4,'class','logo','src','assets/images/marker_flood.svg'),(null as any));
    this._text_15 = this.renderer.createText(this._el_8,'\n                ',(null as any));
    this._text_16 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_6,'div',new import3.InlineArray2(2,'class','text-center'),(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'\n                    ',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_17,'span',new import3.InlineArray2(2,'class','login-title text-center'),(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'Flood Front',(null as any));
    this._text_21 = this.renderer.createText(this._el_17,'\n                ',(null as any));
    this._text_22 = this.renderer.createText(this._el_6,'\n            ',(null as any));
    this._text_23 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._text_24 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_25 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_26 = this.renderer.createText(this._el_25,'\n            ',(null as any));
    this._el_27 = import3.createRenderElement(this.renderer,this._el_25,'div',new import3.InlineArray2(2,'class','col-md-12 col-sm-12 col-xs-12'),(null as any));
    this._text_28 = this.renderer.createText(this._el_27,'\n                ',(null as any));
    this._el_29 = import3.createRenderElement(this.renderer,this._el_27,'div',new import3.InlineArray4(4,'class','login-container','style','width:100%;'),(null as any));
    this._text_30 = this.renderer.createText(this._el_29,'\n                    ',(null as any));
    this._el_31 = import3.createRenderElement(this.renderer,this._el_29,'div',new import3.InlineArray4(4,'class','input-group','style','width: 75%; margin: 0 auto;'),(null as any));
    this._text_32 = this.renderer.createText(this._el_31,'\n                        ',(null as any));
    this._el_33 = import3.createRenderElement(this.renderer,this._el_31,'span',new import3.InlineArray2(2,'class','input-group-addon'),(null as any));
    this._text_34 = this.renderer.createText(this._el_33,'\n                            ',(null as any));
    this._el_35 = import3.createRenderElement(this.renderer,this._el_33,'span',new import3.InlineArray2(2,'class','glyphicon glyphicon-envelope'),(null as any));
    this._text_36 = this.renderer.createText(this._el_33,'\n                        ',(null as any));
    this._text_37 = this.renderer.createText(this._el_31,'\n                        ',(null as any));
    this._el_38 = import3.createRenderElement(this.renderer,this._el_31,'input',new import3.InlineArray8(6,'class','form-control','placeholder','Email','type','text'),(null as any));
    this._DefaultValueAccessor_38_3 = new import9.Wrapper_DefaultValueAccessor(this.renderer,new import13.ElementRef(this._el_38));
    this._NG_VALUE_ACCESSOR_38_4 = [this._DefaultValueAccessor_38_3.context];
    this._NgModel_38_5 = new import10.Wrapper_NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_38_4);
    this._NgControl_38_6 = this._NgModel_38_5.context;
    this._NgControlStatus_38_7 = new import11.Wrapper_NgControlStatus(this._NgControl_38_6);
    this._text_39 = this.renderer.createText(this._el_31,'\n                        ',(null as any));
    this._el_40 = import3.createRenderElement(this.renderer,this._el_31,'span',new import3.InlineArray2(2,'class','input-group-btn'),(null as any));
    this._text_41 = this.renderer.createText(this._el_40,'\n                            ',(null as any));
    this._el_42 = import3.createRenderElement(this.renderer,this._el_40,'button',new import3.InlineArray2(2,'class','btn btn-default'),(null as any));
    this._text_43 = this.renderer.createText(this._el_42,'ENTER',(null as any));
    this._text_44 = this.renderer.createText(this._el_40,'\n                        ',(null as any));
    this._text_45 = this.renderer.createText(this._el_31,'\n                    ',(null as any));
    this._text_46 = this.renderer.createText(this._el_29,'\n                ',(null as any));
    this._text_47 = this.renderer.createText(this._el_27,'\n\n            ',(null as any));
    this._text_48 = this.renderer.createText(this._el_25,'\n        ',(null as any));
    this._text_49 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_50 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_51 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_38,new import3.InlineArray8(8,'keyup.enter',(null as any),'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_38));
    this._NgModel_38_5.subscribe(this,this.eventHandler(this.handleEvent_38),true);
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_42,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_42));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._text_44,
      this._text_45,
      this._text_46,
      this._text_47,
      this._text_48,
      this._text_49,
      this._text_50,
      this._text_51
    ]
    ),[
      disposable_0,
      disposable_1
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.DefaultValueAccessor) && (38 === requestNodeIndex))) { return this._DefaultValueAccessor_38_3.context; }
    if (((token === import15.NG_VALUE_ACCESSOR) && (38 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_38_4; }
    if (((token === import16.NgModel) && (38 === requestNodeIndex))) { return this._NgModel_38_5.context; }
    if (((token === import17.NgControl) && (38 === requestNodeIndex))) { return this._NgControl_38_6; }
    if (((token === import18.NgControlStatus) && (38 === requestNodeIndex))) { return this._NgControlStatus_38_7.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._DefaultValueAccessor_38_3.ngDoCheck(this,this._el_38,throwOnChange);
    const currVal_38_1_0:any = this.context.email;
    this._NgModel_38_5.check_model(currVal_38_1_0,throwOnChange,false);
    this._NgModel_38_5.ngDoCheck(this,this._el_38,throwOnChange);
    this._NgControlStatus_38_7.ngDoCheck(this,this._el_38,throwOnChange);
    this._NgControlStatus_38_7.checkHost(this,this,this._el_38,throwOnChange);
    const currVal_57:any = this.context.buttonState();
    if (import3.checkBinding(throwOnChange,this._expr_57,currVal_57)) {
      this.renderer.setElementProperty(this._el_42,'disabled',currVal_57);
      this._expr_57 = currVal_57;
    }
  }
  destroyInternal():void {
    this._NgModel_38_5.ngOnDestroy();
  }
  handleEvent_38(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_38_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'keyup.enter')) {
      const pd_sub_0:any = ((<any>this.context.login()) !== false);
      result = (pd_sub_0 && result);
    }
    if ((eventName == 'ngModelChange')) {
      const pd_sub_1:any = ((<any>(this.context.email = $event)) !== false);
      result = (pd_sub_1 && result);
    }
    return result;
  }
  handleEvent_42(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.login()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}