/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.mode-title[_ngcontent-%COMP%] {\n    text-align: center;\n    color: white;\n    font-size: 3em;\n    margin: 5%;\n}\n\n.mode-button[_ngcontent-%COMP%] {\n    margin: 3%;\n    font-size: 5em;\n    text-align: center;\n    background-color: black;\n    color: white;\n}'];