/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../app/event/event.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../../app/shared/environment.service';
import * as import9 from '../../../app/shared/rest.service';
import * as import10 from '../../../app/event/event.service';
import * as import11 from '@angular/router/src/router';
import * as import12 from '../../../app/shared/navigation.service';
import * as import13 from '@angular/core/src/linker/view_container';
import * as import14 from '@angular/core/src/change_detection/change_detection_util';
import * as import15 from '../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import16 from '../../node_modules/@angular/forms/src/directives/ng_form.ngfactory';
import * as import17 from '../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import18 from '../../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import19 from '../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import20 from '@angular/core/src/linker/template_ref';
import * as import21 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import22 from '@angular/core/src/linker/element_ref';
import * as import23 from '@angular/common/src/directives/ng_for';
import * as import24 from '@angular/forms/src/directives/ng_form';
import * as import25 from '@angular/forms/src/directives/control_container';
import * as import26 from '@angular/forms/src/directives/ng_control_status';
import * as import27 from '@angular/forms/src/directives/default_value_accessor';
import * as import28 from '@angular/forms/src/directives/control_value_accessor';
import * as import29 from '@angular/forms/src/directives/ng_model';
import * as import30 from '@angular/forms/src/directives/ng_control';
export class Wrapper_EventComponent {
  /*private*/ _eventHandler:Function;
  context:import0.EventComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any,p4:any) {
    this._changed = false;
    this.context = new import0.EventComponent(p0,p1,p2,p3,p4);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_EventComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_EventComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.EventComponent>;
  _EventComponent_0_3:Wrapper_EventComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_EventComponent_Host0,renderType_EventComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'event-component',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_EventComponent0(this.viewUtils,this,0,this._el_0);
    this._EventComponent_0_3 = new Wrapper_EventComponent(this.injectorGet(import8.EnvironmentService,this.parentIndex),this.injectorGet(import9.RestService,this.parentIndex),this.injectorGet(import10.EventService,this.parentIndex),this.injectorGet(import11.Router,this.parentIndex),this.injectorGet(import12.NavigationService,this.parentIndex));
    this.compView_0.create(this._EventComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._EventComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.EventComponent) && (0 === requestNodeIndex))) { return this._EventComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._EventComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const EventComponentNgFactory:import7.ComponentFactory<import0.EventComponent> = new import7.ComponentFactory<import0.EventComponent>('event-component',View_EventComponent_Host0,import0.EventComponent);
const styles_EventComponent:any[] = ([] as any[]);
class View_EventComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import13.ViewContainer) {
    super(View_EventComponent1,renderType_EventComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_19 = import14.UNINITIALIZED;
    this._expr_20 = import14.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','thumbnail col-xs-12 col-md-6 col-lg-4'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'img',new import3.InlineArray2(2,'src','https://placehold.it/350x150'),(null as any));
    this._text_3 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','caption'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n                ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'h3',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n                ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_4,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'',(null as any));
    this._text_11 = this.renderer.createText(this._el_4,'\n                ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_4,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'\n                    ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_12,'button',new import3.InlineArray2(2,'class','btn btn-primary'),(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'ENTER',(null as any));
    this._text_16 = this.renderer.createText(this._el_12,'\n                ',(null as any));
    this._text_17 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._text_18 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_14,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_14));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._text_18
    ]
    ),[disposable_0]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_19:any = import3.inlineInterpolate(1,'',this.context.$implicit.name,'');
    if (import3.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setText(this._text_7,currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_20:any = import3.inlineInterpolate(1,'',this.context.$implicit.description,'');
    if (import3.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setText(this._text_10,currVal_20);
      this._expr_20 = currVal_20;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_14(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.enterEvent(this.context.$implicit.id,this.context.$implicit.name,this.context.$implicit.bounds)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
var renderType_EventComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_EventComponent,{});
export class View_EventComponent0 extends import1.AppView<import0.EventComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _anchor_4:any;
  /*private*/ _vc_4:import13.ViewContainer;
  _TemplateRef_4_5:any;
  _NgFor_4_6:import15.Wrapper_NgFor;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _NgForm_7_3:import16.Wrapper_NgForm;
  _ControlContainer_7_4:any;
  _NgControlStatusGroup_7_5:import17.Wrapper_NgControlStatusGroup;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _NgForm_18_3:import16.Wrapper_NgForm;
  _ControlContainer_18_4:any;
  _NgControlStatusGroup_18_5:import17.Wrapper_NgControlStatusGroup;
  _text_19:any;
  _el_20:any;
  _el_21:any;
  _DefaultValueAccessor_21_3:import18.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_21_4:any[];
  _NgModel_21_5:import19.Wrapper_NgModel;
  _NgControl_21_6:any;
  _NgControlStatus_21_7:import17.Wrapper_NgControlStatus;
  _text_22:any;
  _el_23:any;
  _el_24:any;
  _DefaultValueAccessor_24_3:import18.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_24_4:any[];
  _NgModel_24_5:import19.Wrapper_NgModel;
  _NgControl_24_6:any;
  _NgControlStatus_24_7:import17.Wrapper_NgControlStatus;
  _text_25:any;
  _el_26:any;
  _el_27:any;
  _DefaultValueAccessor_27_3:import18.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_27_4:any[];
  _NgModel_27_5:import19.Wrapper_NgModel;
  _NgControl_27_6:any;
  _NgControlStatus_27_7:import17.Wrapper_NgControlStatus;
  _text_28:any;
  _el_29:any;
  _el_30:any;
  _DefaultValueAccessor_30_3:import18.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_30_4:any[];
  _NgModel_30_5:import19.Wrapper_NgModel;
  _NgControl_30_6:any;
  _NgControlStatus_30_7:import17.Wrapper_NgControlStatus;
  _text_31:any;
  _el_32:any;
  _el_33:any;
  _DefaultValueAccessor_33_3:import18.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_33_4:any[];
  _NgModel_33_5:import19.Wrapper_NgModel;
  _NgControl_33_6:any;
  _NgControlStatus_33_7:import17.Wrapper_NgControlStatus;
  _text_34:any;
  _el_35:any;
  _el_36:any;
  _DefaultValueAccessor_36_3:import18.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_36_4:any[];
  _NgModel_36_5:import19.Wrapper_NgModel;
  _NgControl_36_6:any;
  _NgControlStatus_36_7:import17.Wrapper_NgControlStatus;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _text_40:any;
  _text_41:any;
  _text_42:any;
  /*private*/ _expr_82:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_EventComponent0,renderType_EventComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._expr_82 = import14.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','event-list-container container'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._anchor_4 = this.renderer.createTemplateAnchor(this._el_2,(null as any));
    this._vc_4 = new import13.ViewContainer(4,2,this,this._anchor_4);
    this._TemplateRef_4_5 = new import20.TemplateRef_(this,4,this._anchor_4);
    this._NgFor_4_6 = new import15.Wrapper_NgFor(this._vc_4.vcRef,this._TemplateRef_4_5,this.parentView.injectorGet(import21.IterableDiffers,this.parentIndex),this.ref);
    this._text_5 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_6 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_0,'form',new import3.InlineArray8(6,'action','https://localhost:8080/upload','enctype','multipart/form-data','method','POST'),(null as any));
    this._NgForm_7_3 = new import16.Wrapper_NgForm((null as any),(null as any));
    this._ControlContainer_7_4 = this._NgForm_7_3.context;
    this._NgControlStatusGroup_7_5 = new import17.Wrapper_NgControlStatusGroup(this._ControlContainer_7_4);
    this._text_8 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_7,'input',new import3.InlineArray8(6,'accept','image/*','name','picture','type','file'),(null as any));
    this._text_10 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_7,'img',new import3.InlineArray8(6,'id','test','onchange','console.log(\'changed\')','src','#'),(null as any));
    this._text_12 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._text_13 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_7,'button',new import3.InlineArray2(2,'class','btn btn-default'),(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'UPLOAD',(null as any));
    this._text_16 = this.renderer.createText(this._el_7,'\n    ',(null as any));
    this._text_17 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_0,'form',new import3.InlineArray2(2,'class','form-inline'),(null as any));
    this._NgForm_18_3 = new import16.Wrapper_NgForm((null as any),(null as any));
    this._ControlContainer_18_4 = this._NgForm_18_3.context;
    this._NgControlStatusGroup_18_5 = new import17.Wrapper_NgControlStatusGroup(this._ControlContainer_18_4);
    this._text_19 = this.renderer.createText(this._el_18,'\n        ',(null as any));
    this._el_20 = import3.createRenderElement(this.renderer,this._el_18,'div',new import3.InlineArray2(2,'class','form group'),(null as any));
    this._el_21 = import3.createRenderElement(this.renderer,this._el_20,'input',new import3.InlineArray8(8,'class','form-control','name','name','placeholder','Event name','type','text'),(null as any));
    this._DefaultValueAccessor_21_3 = new import18.Wrapper_DefaultValueAccessor(this.renderer,new import22.ElementRef(this._el_21));
    this._NG_VALUE_ACCESSOR_21_4 = [this._DefaultValueAccessor_21_3.context];
    this._NgModel_21_5 = new import19.Wrapper_NgModel(this._ControlContainer_18_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_21_4);
    this._NgControl_21_6 = this._NgModel_21_5.context;
    this._NgControlStatus_21_7 = new import17.Wrapper_NgControlStatus(this._NgControl_21_6);
    this._text_22 = this.renderer.createText(this._el_18,'\n        ',(null as any));
    this._el_23 = import3.createRenderElement(this.renderer,this._el_18,'div',new import3.InlineArray2(2,'class','form group'),(null as any));
    this._el_24 = import3.createRenderElement(this.renderer,this._el_23,'input',new import3.InlineArray8(8,'class','form-control','name','description','placeholder','Desc.','type','text'),(null as any));
    this._DefaultValueAccessor_24_3 = new import18.Wrapper_DefaultValueAccessor(this.renderer,new import22.ElementRef(this._el_24));
    this._NG_VALUE_ACCESSOR_24_4 = [this._DefaultValueAccessor_24_3.context];
    this._NgModel_24_5 = new import19.Wrapper_NgModel(this._ControlContainer_18_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_24_4);
    this._NgControl_24_6 = this._NgModel_24_5.context;
    this._NgControlStatus_24_7 = new import17.Wrapper_NgControlStatus(this._NgControl_24_6);
    this._text_25 = this.renderer.createText(this._el_18,'\n        ',(null as any));
    this._el_26 = import3.createRenderElement(this.renderer,this._el_18,'div',new import3.InlineArray2(2,'class','form group'),(null as any));
    this._el_27 = import3.createRenderElement(this.renderer,this._el_26,'input',new import3.InlineArray8(8,'class','form-control','name','minLat','placeholder','Min lat','type','text'),(null as any));
    this._DefaultValueAccessor_27_3 = new import18.Wrapper_DefaultValueAccessor(this.renderer,new import22.ElementRef(this._el_27));
    this._NG_VALUE_ACCESSOR_27_4 = [this._DefaultValueAccessor_27_3.context];
    this._NgModel_27_5 = new import19.Wrapper_NgModel(this._ControlContainer_18_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_27_4);
    this._NgControl_27_6 = this._NgModel_27_5.context;
    this._NgControlStatus_27_7 = new import17.Wrapper_NgControlStatus(this._NgControl_27_6);
    this._text_28 = this.renderer.createText(this._el_18,'\n        ',(null as any));
    this._el_29 = import3.createRenderElement(this.renderer,this._el_18,'div',new import3.InlineArray2(2,'class','form group'),(null as any));
    this._el_30 = import3.createRenderElement(this.renderer,this._el_29,'input',new import3.InlineArray8(8,'class','form-control','name','minLon','placeholder','Min lon','type','text'),(null as any));
    this._DefaultValueAccessor_30_3 = new import18.Wrapper_DefaultValueAccessor(this.renderer,new import22.ElementRef(this._el_30));
    this._NG_VALUE_ACCESSOR_30_4 = [this._DefaultValueAccessor_30_3.context];
    this._NgModel_30_5 = new import19.Wrapper_NgModel(this._ControlContainer_18_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_30_4);
    this._NgControl_30_6 = this._NgModel_30_5.context;
    this._NgControlStatus_30_7 = new import17.Wrapper_NgControlStatus(this._NgControl_30_6);
    this._text_31 = this.renderer.createText(this._el_18,'\n        ',(null as any));
    this._el_32 = import3.createRenderElement(this.renderer,this._el_18,'div',new import3.InlineArray2(2,'class','form group'),(null as any));
    this._el_33 = import3.createRenderElement(this.renderer,this._el_32,'input',new import3.InlineArray8(8,'class','form-control','name','maxLat','placeholder','Max lat','type','text'),(null as any));
    this._DefaultValueAccessor_33_3 = new import18.Wrapper_DefaultValueAccessor(this.renderer,new import22.ElementRef(this._el_33));
    this._NG_VALUE_ACCESSOR_33_4 = [this._DefaultValueAccessor_33_3.context];
    this._NgModel_33_5 = new import19.Wrapper_NgModel(this._ControlContainer_18_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_33_4);
    this._NgControl_33_6 = this._NgModel_33_5.context;
    this._NgControlStatus_33_7 = new import17.Wrapper_NgControlStatus(this._NgControl_33_6);
    this._text_34 = this.renderer.createText(this._el_18,'\n        ',(null as any));
    this._el_35 = import3.createRenderElement(this.renderer,this._el_18,'div',new import3.InlineArray2(2,'class','form group'),(null as any));
    this._el_36 = import3.createRenderElement(this.renderer,this._el_35,'input',new import3.InlineArray8(8,'class','form-control','name','maxLon','placeholder','Max lon','type','text'),(null as any));
    this._DefaultValueAccessor_36_3 = new import18.Wrapper_DefaultValueAccessor(this.renderer,new import22.ElementRef(this._el_36));
    this._NG_VALUE_ACCESSOR_36_4 = [this._DefaultValueAccessor_36_3.context];
    this._NgModel_36_5 = new import19.Wrapper_NgModel(this._ControlContainer_18_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_36_4);
    this._NgControl_36_6 = this._NgModel_36_5.context;
    this._NgControlStatus_36_7 = new import17.Wrapper_NgControlStatus(this._NgControl_36_6);
    this._text_37 = this.renderer.createText(this._el_18,'\n        ',(null as any));
    this._el_38 = import3.createRenderElement(this.renderer,this._el_18,'button',new import3.InlineArray2(2,'class','btn btn-default'),(null as any));
    this._text_39 = this.renderer.createText(this._el_38,'CREATE EVENT',(null as any));
    this._text_40 = this.renderer.createText(this._el_18,'\n    ',(null as any));
    this._text_41 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._text_42 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_7,new import3.InlineArray4(4,'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_7));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_9,new import3.InlineArray2(2,'change',(null as any)),this.eventHandler(this.handleEvent_9));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_14,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_14));
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_18,new import3.InlineArray4(4,'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_18));
    var disposable_4:Function = import3.subscribeToRenderElement(this,this._el_21,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_21));
    this._NgModel_21_5.subscribe(this,this.eventHandler(this.handleEvent_21),true);
    var disposable_5:Function = import3.subscribeToRenderElement(this,this._el_24,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_24));
    this._NgModel_24_5.subscribe(this,this.eventHandler(this.handleEvent_24),true);
    var disposable_6:Function = import3.subscribeToRenderElement(this,this._el_27,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_27));
    this._NgModel_27_5.subscribe(this,this.eventHandler(this.handleEvent_27),true);
    var disposable_7:Function = import3.subscribeToRenderElement(this,this._el_30,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_30));
    this._NgModel_30_5.subscribe(this,this.eventHandler(this.handleEvent_30),true);
    var disposable_8:Function = import3.subscribeToRenderElement(this,this._el_33,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_33));
    this._NgModel_33_5.subscribe(this,this.eventHandler(this.handleEvent_33),true);
    var disposable_9:Function = import3.subscribeToRenderElement(this,this._el_36,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_36));
    this._NgModel_36_5.subscribe(this,this.eventHandler(this.handleEvent_36),true);
    var disposable_10:Function = import3.subscribeToRenderElement(this,this._el_38,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_38));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._anchor_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._el_27,
      this._text_28,
      this._el_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._el_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._text_40,
      this._text_41,
      this._text_42
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7,
      disposable_8,
      disposable_9,
      disposable_10
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import20.TemplateRef) && (4 === requestNodeIndex))) { return this._TemplateRef_4_5; }
    if (((token === import23.NgFor) && (4 === requestNodeIndex))) { return this._NgFor_4_6.context; }
    if (((token === import24.NgForm) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._NgForm_7_3.context; }
    if (((token === import25.ControlContainer) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._ControlContainer_7_4; }
    if (((token === import26.NgControlStatusGroup) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._NgControlStatusGroup_7_5.context; }
    if (((token === import27.DefaultValueAccessor) && (21 === requestNodeIndex))) { return this._DefaultValueAccessor_21_3.context; }
    if (((token === import28.NG_VALUE_ACCESSOR) && (21 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_21_4; }
    if (((token === import29.NgModel) && (21 === requestNodeIndex))) { return this._NgModel_21_5.context; }
    if (((token === import30.NgControl) && (21 === requestNodeIndex))) { return this._NgControl_21_6; }
    if (((token === import26.NgControlStatus) && (21 === requestNodeIndex))) { return this._NgControlStatus_21_7.context; }
    if (((token === import27.DefaultValueAccessor) && (24 === requestNodeIndex))) { return this._DefaultValueAccessor_24_3.context; }
    if (((token === import28.NG_VALUE_ACCESSOR) && (24 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_24_4; }
    if (((token === import29.NgModel) && (24 === requestNodeIndex))) { return this._NgModel_24_5.context; }
    if (((token === import30.NgControl) && (24 === requestNodeIndex))) { return this._NgControl_24_6; }
    if (((token === import26.NgControlStatus) && (24 === requestNodeIndex))) { return this._NgControlStatus_24_7.context; }
    if (((token === import27.DefaultValueAccessor) && (27 === requestNodeIndex))) { return this._DefaultValueAccessor_27_3.context; }
    if (((token === import28.NG_VALUE_ACCESSOR) && (27 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_27_4; }
    if (((token === import29.NgModel) && (27 === requestNodeIndex))) { return this._NgModel_27_5.context; }
    if (((token === import30.NgControl) && (27 === requestNodeIndex))) { return this._NgControl_27_6; }
    if (((token === import26.NgControlStatus) && (27 === requestNodeIndex))) { return this._NgControlStatus_27_7.context; }
    if (((token === import27.DefaultValueAccessor) && (30 === requestNodeIndex))) { return this._DefaultValueAccessor_30_3.context; }
    if (((token === import28.NG_VALUE_ACCESSOR) && (30 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_30_4; }
    if (((token === import29.NgModel) && (30 === requestNodeIndex))) { return this._NgModel_30_5.context; }
    if (((token === import30.NgControl) && (30 === requestNodeIndex))) { return this._NgControl_30_6; }
    if (((token === import26.NgControlStatus) && (30 === requestNodeIndex))) { return this._NgControlStatus_30_7.context; }
    if (((token === import27.DefaultValueAccessor) && (33 === requestNodeIndex))) { return this._DefaultValueAccessor_33_3.context; }
    if (((token === import28.NG_VALUE_ACCESSOR) && (33 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_33_4; }
    if (((token === import29.NgModel) && (33 === requestNodeIndex))) { return this._NgModel_33_5.context; }
    if (((token === import30.NgControl) && (33 === requestNodeIndex))) { return this._NgControl_33_6; }
    if (((token === import26.NgControlStatus) && (33 === requestNodeIndex))) { return this._NgControlStatus_33_7.context; }
    if (((token === import27.DefaultValueAccessor) && (36 === requestNodeIndex))) { return this._DefaultValueAccessor_36_3.context; }
    if (((token === import28.NG_VALUE_ACCESSOR) && (36 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_36_4; }
    if (((token === import29.NgModel) && (36 === requestNodeIndex))) { return this._NgModel_36_5.context; }
    if (((token === import30.NgControl) && (36 === requestNodeIndex))) { return this._NgControl_36_6; }
    if (((token === import26.NgControlStatus) && (36 === requestNodeIndex))) { return this._NgControlStatus_36_7.context; }
    if (((token === import24.NgForm) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 40)))) { return this._NgForm_18_3.context; }
    if (((token === import25.ControlContainer) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 40)))) { return this._ControlContainer_18_4; }
    if (((token === import26.NgControlStatusGroup) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 40)))) { return this._NgControlStatusGroup_18_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_4_0_0:any = this.context.events;
    this._NgFor_4_6.check_ngForOf(currVal_4_0_0,throwOnChange,false);
    this._NgFor_4_6.ngDoCheck(this,this._anchor_4,throwOnChange);
    this._NgForm_7_3.ngDoCheck(this,this._el_7,throwOnChange);
    this._NgControlStatusGroup_7_5.ngDoCheck(this,this._el_7,throwOnChange);
    this._NgForm_18_3.ngDoCheck(this,this._el_18,throwOnChange);
    this._NgControlStatusGroup_18_5.ngDoCheck(this,this._el_18,throwOnChange);
    this._DefaultValueAccessor_21_3.ngDoCheck(this,this._el_21,throwOnChange);
    const currVal_21_1_0:any = 'name';
    this._NgModel_21_5.check_name(currVal_21_1_0,throwOnChange,false);
    const currVal_21_1_1:any = this.context.eventName;
    this._NgModel_21_5.check_model(currVal_21_1_1,throwOnChange,false);
    this._NgModel_21_5.ngDoCheck(this,this._el_21,throwOnChange);
    this._NgControlStatus_21_7.ngDoCheck(this,this._el_21,throwOnChange);
    this._DefaultValueAccessor_24_3.ngDoCheck(this,this._el_24,throwOnChange);
    const currVal_24_1_0:any = 'description';
    this._NgModel_24_5.check_name(currVal_24_1_0,throwOnChange,false);
    const currVal_24_1_1:any = this.context.description;
    this._NgModel_24_5.check_model(currVal_24_1_1,throwOnChange,false);
    this._NgModel_24_5.ngDoCheck(this,this._el_24,throwOnChange);
    this._NgControlStatus_24_7.ngDoCheck(this,this._el_24,throwOnChange);
    this._DefaultValueAccessor_27_3.ngDoCheck(this,this._el_27,throwOnChange);
    const currVal_27_1_0:any = 'minLat';
    this._NgModel_27_5.check_name(currVal_27_1_0,throwOnChange,false);
    const currVal_27_1_1:any = this.context.minLat;
    this._NgModel_27_5.check_model(currVal_27_1_1,throwOnChange,false);
    this._NgModel_27_5.ngDoCheck(this,this._el_27,throwOnChange);
    this._NgControlStatus_27_7.ngDoCheck(this,this._el_27,throwOnChange);
    this._DefaultValueAccessor_30_3.ngDoCheck(this,this._el_30,throwOnChange);
    const currVal_30_1_0:any = 'minLon';
    this._NgModel_30_5.check_name(currVal_30_1_0,throwOnChange,false);
    const currVal_30_1_1:any = this.context.minLon;
    this._NgModel_30_5.check_model(currVal_30_1_1,throwOnChange,false);
    this._NgModel_30_5.ngDoCheck(this,this._el_30,throwOnChange);
    this._NgControlStatus_30_7.ngDoCheck(this,this._el_30,throwOnChange);
    this._DefaultValueAccessor_33_3.ngDoCheck(this,this._el_33,throwOnChange);
    const currVal_33_1_0:any = 'maxLat';
    this._NgModel_33_5.check_name(currVal_33_1_0,throwOnChange,false);
    const currVal_33_1_1:any = this.context.maxLat;
    this._NgModel_33_5.check_model(currVal_33_1_1,throwOnChange,false);
    this._NgModel_33_5.ngDoCheck(this,this._el_33,throwOnChange);
    this._NgControlStatus_33_7.ngDoCheck(this,this._el_33,throwOnChange);
    this._DefaultValueAccessor_36_3.ngDoCheck(this,this._el_36,throwOnChange);
    const currVal_36_1_0:any = 'maxLon';
    this._NgModel_36_5.check_name(currVal_36_1_0,throwOnChange,false);
    const currVal_36_1_1:any = this.context.maxLon;
    this._NgModel_36_5.check_model(currVal_36_1_1,throwOnChange,false);
    this._NgModel_36_5.ngDoCheck(this,this._el_36,throwOnChange);
    this._NgControlStatus_36_7.ngDoCheck(this,this._el_36,throwOnChange);
    this._vc_4.detectChangesInNestedViews(throwOnChange);
    this._NgControlStatusGroup_7_5.checkHost(this,this,this._el_7,throwOnChange);
    this._NgControlStatusGroup_18_5.checkHost(this,this,this._el_18,throwOnChange);
    this._NgControlStatus_21_7.checkHost(this,this,this._el_21,throwOnChange);
    this._NgControlStatus_24_7.checkHost(this,this,this._el_24,throwOnChange);
    this._NgControlStatus_27_7.checkHost(this,this,this._el_27,throwOnChange);
    this._NgControlStatus_30_7.checkHost(this,this,this._el_30,throwOnChange);
    this._NgControlStatus_33_7.checkHost(this,this,this._el_33,throwOnChange);
    this._NgControlStatus_36_7.checkHost(this,this,this._el_36,throwOnChange);
    const currVal_82:any = this.context.createEventButtonState();
    if (import3.checkBinding(throwOnChange,this._expr_82,currVal_82)) {
      this.renderer.setElementProperty(this._el_38,'disabled',currVal_82);
      this._expr_82 = currVal_82;
    }
  }
  destroyInternal():void {
    this._vc_4.destroyNestedViews();
    this._NgForm_7_3.ngOnDestroy();
    this._NgModel_21_5.ngOnDestroy();
    this._NgModel_24_5.ngOnDestroy();
    this._NgModel_27_5.ngOnDestroy();
    this._NgModel_30_5.ngOnDestroy();
    this._NgModel_33_5.ngOnDestroy();
    this._NgModel_36_5.ngOnDestroy();
    this._NgForm_18_3.ngOnDestroy();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 4)) { return new View_EventComponent1(this.viewUtils,this,4,this._anchor_4,this._vc_4); }
    return (null as any);
  }
  handleEvent_7(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._NgForm_7_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_9(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'change')) {
      const pd_sub_0:any = ((<any>this.context.readUrl($event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_14(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.uploadImage()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_18(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._NgForm_18_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_21(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_21_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.eventName = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_24(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_24_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.description = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_27(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_27_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.minLat = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_30(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_30_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.minLon = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_33(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_33_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.maxLat = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_36(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_36_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.maxLon = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_38(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.createEvent()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}