/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../app/event/event.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../../app/shared/environment.service';
import * as import9 from '../../../app/shared/rest.service';
import * as import10 from '../../../app/event/event.service';
import * as import11 from '@angular/router/src/router';
import * as import12 from '@angular/core/src/linker/view_container';
import * as import13 from '@angular/core/src/change_detection/change_detection_util';
import * as import14 from '../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import15 from '../../node_modules/@angular/forms/src/directives/ng_form.ngfactory';
import * as import16 from '../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import17 from '../../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import18 from '../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import19 from '@angular/core/src/linker/template_ref';
import * as import20 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import21 from '@angular/core/src/linker/element_ref';
import * as import22 from '@angular/common/src/directives/ng_for';
import * as import23 from '@angular/forms/src/directives/ng_form';
import * as import24 from '@angular/forms/src/directives/control_container';
import * as import25 from '@angular/forms/src/directives/ng_control_status';
import * as import26 from '@angular/forms/src/directives/default_value_accessor';
import * as import27 from '@angular/forms/src/directives/control_value_accessor';
import * as import28 from '@angular/forms/src/directives/ng_model';
import * as import29 from '@angular/forms/src/directives/ng_control';
export class Wrapper_EventComponent {
  /*private*/ _eventHandler:Function;
  context:import0.EventComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any) {
    this._changed = false;
    this.context = new import0.EventComponent(p0,p1,p2,p3);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_EventComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_EventComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.EventComponent>;
  _EventComponent_0_3:Wrapper_EventComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_EventComponent_Host0,renderType_EventComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'event-component',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_EventComponent0(this.viewUtils,this,0,this._el_0);
    this._EventComponent_0_3 = new Wrapper_EventComponent(this.injectorGet(import8.EnvironmentService,this.parentIndex),this.injectorGet(import9.RestService,this.parentIndex),this.injectorGet(import10.EventService,this.parentIndex),this.injectorGet(import11.Router,this.parentIndex));
    this.compView_0.create(this._EventComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._EventComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.EventComponent) && (0 === requestNodeIndex))) { return this._EventComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._EventComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const EventComponentNgFactory:import7.ComponentFactory<import0.EventComponent> = new import7.ComponentFactory<import0.EventComponent>('event-component',View_EventComponent_Host0,import0.EventComponent);
const styles_EventComponent:any[] = ([] as any[]);
class View_EventComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_EventComponent1,renderType_EventComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_19 = import13.UNINITIALIZED;
    this._expr_20 = import13.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','thumbnail col-xs-12 col-md-6 col-lg-4'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'img',new import3.InlineArray2(2,'src','https://placehold.it/350x150'),(null as any));
    this._text_3 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','caption'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n                ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'h3',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n                ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_4,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'',(null as any));
    this._text_11 = this.renderer.createText(this._el_4,'\n                ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_4,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'\n                    ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_12,'button',new import3.InlineArray2(2,'class','btn btn-primary'),(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'ENTER',(null as any));
    this._text_16 = this.renderer.createText(this._el_12,'\n                ',(null as any));
    this._text_17 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._text_18 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_14,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_14));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._text_18
    ]
    ),[disposable_0]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_19:any = import3.inlineInterpolate(1,'',this.context.$implicit.name,'');
    if (import3.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setText(this._text_7,currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_20:any = import3.inlineInterpolate(1,'',this.context.$implicit.description,'');
    if (import3.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setText(this._text_10,currVal_20);
      this._expr_20 = currVal_20;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_14(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.enterEvent(this.context.$implicit.id,this.context.$implicit.name,this.context.$implicit.bounds)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
var renderType_EventComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_EventComponent,{});
export class View_EventComponent0 extends import1.AppView<import0.EventComponent> {
  _el_0:any;
  _text_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _anchor_5:any;
  /*private*/ _vc_5:import12.ViewContainer;
  _TemplateRef_5_5:any;
  _NgFor_5_6:import14.Wrapper_NgFor;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _NgForm_8_3:import15.Wrapper_NgForm;
  _ControlContainer_8_4:any;
  _NgControlStatusGroup_8_5:import16.Wrapper_NgControlStatusGroup;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _NgForm_19_3:import15.Wrapper_NgForm;
  _ControlContainer_19_4:any;
  _NgControlStatusGroup_19_5:import16.Wrapper_NgControlStatusGroup;
  _text_20:any;
  _el_21:any;
  _el_22:any;
  _DefaultValueAccessor_22_3:import17.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_22_4:any[];
  _NgModel_22_5:import18.Wrapper_NgModel;
  _NgControl_22_6:any;
  _NgControlStatus_22_7:import16.Wrapper_NgControlStatus;
  _text_23:any;
  _el_24:any;
  _el_25:any;
  _DefaultValueAccessor_25_3:import17.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_25_4:any[];
  _NgModel_25_5:import18.Wrapper_NgModel;
  _NgControl_25_6:any;
  _NgControlStatus_25_7:import16.Wrapper_NgControlStatus;
  _text_26:any;
  _el_27:any;
  _el_28:any;
  _DefaultValueAccessor_28_3:import17.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_28_4:any[];
  _NgModel_28_5:import18.Wrapper_NgModel;
  _NgControl_28_6:any;
  _NgControlStatus_28_7:import16.Wrapper_NgControlStatus;
  _text_29:any;
  _el_30:any;
  _el_31:any;
  _DefaultValueAccessor_31_3:import17.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_31_4:any[];
  _NgModel_31_5:import18.Wrapper_NgModel;
  _NgControl_31_6:any;
  _NgControlStatus_31_7:import16.Wrapper_NgControlStatus;
  _text_32:any;
  _el_33:any;
  _el_34:any;
  _DefaultValueAccessor_34_3:import17.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_34_4:any[];
  _NgModel_34_5:import18.Wrapper_NgModel;
  _NgControl_34_6:any;
  _NgControlStatus_34_7:import16.Wrapper_NgControlStatus;
  _text_35:any;
  _el_36:any;
  _el_37:any;
  _DefaultValueAccessor_37_3:import17.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_37_4:any[];
  _NgModel_37_5:import18.Wrapper_NgModel;
  _NgControl_37_6:any;
  _NgControlStatus_37_7:import16.Wrapper_NgControlStatus;
  _text_38:any;
  _el_39:any;
  _text_40:any;
  _text_41:any;
  _text_42:any;
  _text_43:any;
  /*private*/ _expr_83:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_EventComponent0,renderType_EventComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._expr_83 = import13.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'style','visibility: hidden;'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,' \n    ',(null as any));
    this._text_2 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_3 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','event-list-container container'),(null as any));
    this._text_4 = this.renderer.createText(this._el_3,'\n        ',(null as any));
    this._anchor_5 = this.renderer.createTemplateAnchor(this._el_3,(null as any));
    this._vc_5 = new import12.ViewContainer(5,3,this,this._anchor_5);
    this._TemplateRef_5_5 = new import19.TemplateRef_(this,5,this._anchor_5);
    this._NgFor_5_6 = new import14.Wrapper_NgFor(this._vc_5.vcRef,this._TemplateRef_5_5,this.parentView.injectorGet(import20.IterableDiffers,this.parentIndex),this.ref);
    this._text_6 = this.renderer.createText(this._el_3,'\n    ',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_0,'form',new import3.InlineArray8(6,'action','https://localhost:8080/upload','enctype','multipart/form-data','method','POST'),(null as any));
    this._NgForm_8_3 = new import15.Wrapper_NgForm((null as any),(null as any));
    this._ControlContainer_8_4 = this._NgForm_8_3.context;
    this._NgControlStatusGroup_8_5 = new import16.Wrapper_NgControlStatusGroup(this._ControlContainer_8_4);
    this._text_9 = this.renderer.createText(this._el_8,'\n        ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_8,'input',new import3.InlineArray8(6,'accept','image/*','name','picture','type','file'),(null as any));
    this._text_11 = this.renderer.createText(this._el_8,'\n        ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_8,'img',new import3.InlineArray8(6,'id','test','onchange','console.log(\'changed\')','src','#'),(null as any));
    this._text_13 = this.renderer.createText(this._el_8,'\n        ',(null as any));
    this._text_14 = this.renderer.createText(this._el_8,'\n        ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_8,'button',new import3.InlineArray2(2,'class','btn btn-default'),(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'UPLOAD',(null as any));
    this._text_17 = this.renderer.createText(this._el_8,'\n    ',(null as any));
    this._text_18 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_0,'form',new import3.InlineArray2(2,'class','form-inline'),(null as any));
    this._NgForm_19_3 = new import15.Wrapper_NgForm((null as any),(null as any));
    this._ControlContainer_19_4 = this._NgForm_19_3.context;
    this._NgControlStatusGroup_19_5 = new import16.Wrapper_NgControlStatusGroup(this._ControlContainer_19_4);
    this._text_20 = this.renderer.createText(this._el_19,'\n        ',(null as any));
    this._el_21 = import3.createRenderElement(this.renderer,this._el_19,'div',new import3.InlineArray2(2,'class','form group'),(null as any));
    this._el_22 = import3.createRenderElement(this.renderer,this._el_21,'input',new import3.InlineArray8(8,'class','form-control','name','name','placeholder','Event name','type','text'),(null as any));
    this._DefaultValueAccessor_22_3 = new import17.Wrapper_DefaultValueAccessor(this.renderer,new import21.ElementRef(this._el_22));
    this._NG_VALUE_ACCESSOR_22_4 = [this._DefaultValueAccessor_22_3.context];
    this._NgModel_22_5 = new import18.Wrapper_NgModel(this._ControlContainer_19_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_22_4);
    this._NgControl_22_6 = this._NgModel_22_5.context;
    this._NgControlStatus_22_7 = new import16.Wrapper_NgControlStatus(this._NgControl_22_6);
    this._text_23 = this.renderer.createText(this._el_19,'\n        ',(null as any));
    this._el_24 = import3.createRenderElement(this.renderer,this._el_19,'div',new import3.InlineArray2(2,'class','form group'),(null as any));
    this._el_25 = import3.createRenderElement(this.renderer,this._el_24,'input',new import3.InlineArray8(8,'class','form-control','name','description','placeholder','Desc.','type','text'),(null as any));
    this._DefaultValueAccessor_25_3 = new import17.Wrapper_DefaultValueAccessor(this.renderer,new import21.ElementRef(this._el_25));
    this._NG_VALUE_ACCESSOR_25_4 = [this._DefaultValueAccessor_25_3.context];
    this._NgModel_25_5 = new import18.Wrapper_NgModel(this._ControlContainer_19_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_25_4);
    this._NgControl_25_6 = this._NgModel_25_5.context;
    this._NgControlStatus_25_7 = new import16.Wrapper_NgControlStatus(this._NgControl_25_6);
    this._text_26 = this.renderer.createText(this._el_19,'\n        ',(null as any));
    this._el_27 = import3.createRenderElement(this.renderer,this._el_19,'div',new import3.InlineArray2(2,'class','form group'),(null as any));
    this._el_28 = import3.createRenderElement(this.renderer,this._el_27,'input',new import3.InlineArray8(8,'class','form-control','name','minLat','placeholder','Min lat','type','text'),(null as any));
    this._DefaultValueAccessor_28_3 = new import17.Wrapper_DefaultValueAccessor(this.renderer,new import21.ElementRef(this._el_28));
    this._NG_VALUE_ACCESSOR_28_4 = [this._DefaultValueAccessor_28_3.context];
    this._NgModel_28_5 = new import18.Wrapper_NgModel(this._ControlContainer_19_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_28_4);
    this._NgControl_28_6 = this._NgModel_28_5.context;
    this._NgControlStatus_28_7 = new import16.Wrapper_NgControlStatus(this._NgControl_28_6);
    this._text_29 = this.renderer.createText(this._el_19,'\n        ',(null as any));
    this._el_30 = import3.createRenderElement(this.renderer,this._el_19,'div',new import3.InlineArray2(2,'class','form group'),(null as any));
    this._el_31 = import3.createRenderElement(this.renderer,this._el_30,'input',new import3.InlineArray8(8,'class','form-control','name','minLon','placeholder','Min lon','type','text'),(null as any));
    this._DefaultValueAccessor_31_3 = new import17.Wrapper_DefaultValueAccessor(this.renderer,new import21.ElementRef(this._el_31));
    this._NG_VALUE_ACCESSOR_31_4 = [this._DefaultValueAccessor_31_3.context];
    this._NgModel_31_5 = new import18.Wrapper_NgModel(this._ControlContainer_19_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_31_4);
    this._NgControl_31_6 = this._NgModel_31_5.context;
    this._NgControlStatus_31_7 = new import16.Wrapper_NgControlStatus(this._NgControl_31_6);
    this._text_32 = this.renderer.createText(this._el_19,'\n        ',(null as any));
    this._el_33 = import3.createRenderElement(this.renderer,this._el_19,'div',new import3.InlineArray2(2,'class','form group'),(null as any));
    this._el_34 = import3.createRenderElement(this.renderer,this._el_33,'input',new import3.InlineArray8(8,'class','form-control','name','maxLat','placeholder','Max lat','type','text'),(null as any));
    this._DefaultValueAccessor_34_3 = new import17.Wrapper_DefaultValueAccessor(this.renderer,new import21.ElementRef(this._el_34));
    this._NG_VALUE_ACCESSOR_34_4 = [this._DefaultValueAccessor_34_3.context];
    this._NgModel_34_5 = new import18.Wrapper_NgModel(this._ControlContainer_19_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_34_4);
    this._NgControl_34_6 = this._NgModel_34_5.context;
    this._NgControlStatus_34_7 = new import16.Wrapper_NgControlStatus(this._NgControl_34_6);
    this._text_35 = this.renderer.createText(this._el_19,'\n        ',(null as any));
    this._el_36 = import3.createRenderElement(this.renderer,this._el_19,'div',new import3.InlineArray2(2,'class','form group'),(null as any));
    this._el_37 = import3.createRenderElement(this.renderer,this._el_36,'input',new import3.InlineArray8(8,'class','form-control','name','maxLon','placeholder','Max lon','type','text'),(null as any));
    this._DefaultValueAccessor_37_3 = new import17.Wrapper_DefaultValueAccessor(this.renderer,new import21.ElementRef(this._el_37));
    this._NG_VALUE_ACCESSOR_37_4 = [this._DefaultValueAccessor_37_3.context];
    this._NgModel_37_5 = new import18.Wrapper_NgModel(this._ControlContainer_19_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_37_4);
    this._NgControl_37_6 = this._NgModel_37_5.context;
    this._NgControlStatus_37_7 = new import16.Wrapper_NgControlStatus(this._NgControl_37_6);
    this._text_38 = this.renderer.createText(this._el_19,'\n        ',(null as any));
    this._el_39 = import3.createRenderElement(this.renderer,this._el_19,'button',new import3.InlineArray2(2,'class','btn btn-default'),(null as any));
    this._text_40 = this.renderer.createText(this._el_39,'CREATE EVENT',(null as any));
    this._text_41 = this.renderer.createText(this._el_19,'\n    ',(null as any));
    this._text_42 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._text_43 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_8,new import3.InlineArray4(4,'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_8));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_10,new import3.InlineArray2(2,'change',(null as any)),this.eventHandler(this.handleEvent_10));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_15,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_15));
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_19,new import3.InlineArray4(4,'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_19));
    var disposable_4:Function = import3.subscribeToRenderElement(this,this._el_22,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_22));
    this._NgModel_22_5.subscribe(this,this.eventHandler(this.handleEvent_22),true);
    var disposable_5:Function = import3.subscribeToRenderElement(this,this._el_25,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_25));
    this._NgModel_25_5.subscribe(this,this.eventHandler(this.handleEvent_25),true);
    var disposable_6:Function = import3.subscribeToRenderElement(this,this._el_28,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_28));
    this._NgModel_28_5.subscribe(this,this.eventHandler(this.handleEvent_28),true);
    var disposable_7:Function = import3.subscribeToRenderElement(this,this._el_31,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_31));
    this._NgModel_31_5.subscribe(this,this.eventHandler(this.handleEvent_31),true);
    var disposable_8:Function = import3.subscribeToRenderElement(this,this._el_34,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_34));
    this._NgModel_34_5.subscribe(this,this.eventHandler(this.handleEvent_34),true);
    var disposable_9:Function = import3.subscribeToRenderElement(this,this._el_37,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_37));
    this._NgModel_37_5.subscribe(this,this.eventHandler(this.handleEvent_37),true);
    var disposable_10:Function = import3.subscribeToRenderElement(this,this._el_39,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_39));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._anchor_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._el_31,
      this._text_32,
      this._el_33,
      this._el_34,
      this._text_35,
      this._el_36,
      this._el_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._text_41,
      this._text_42,
      this._text_43
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7,
      disposable_8,
      disposable_9,
      disposable_10
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.TemplateRef) && (5 === requestNodeIndex))) { return this._TemplateRef_5_5; }
    if (((token === import22.NgFor) && (5 === requestNodeIndex))) { return this._NgFor_5_6.context; }
    if (((token === import23.NgForm) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._NgForm_8_3.context; }
    if (((token === import24.ControlContainer) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._ControlContainer_8_4; }
    if (((token === import25.NgControlStatusGroup) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._NgControlStatusGroup_8_5.context; }
    if (((token === import26.DefaultValueAccessor) && (22 === requestNodeIndex))) { return this._DefaultValueAccessor_22_3.context; }
    if (((token === import27.NG_VALUE_ACCESSOR) && (22 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_22_4; }
    if (((token === import28.NgModel) && (22 === requestNodeIndex))) { return this._NgModel_22_5.context; }
    if (((token === import29.NgControl) && (22 === requestNodeIndex))) { return this._NgControl_22_6; }
    if (((token === import25.NgControlStatus) && (22 === requestNodeIndex))) { return this._NgControlStatus_22_7.context; }
    if (((token === import26.DefaultValueAccessor) && (25 === requestNodeIndex))) { return this._DefaultValueAccessor_25_3.context; }
    if (((token === import27.NG_VALUE_ACCESSOR) && (25 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_25_4; }
    if (((token === import28.NgModel) && (25 === requestNodeIndex))) { return this._NgModel_25_5.context; }
    if (((token === import29.NgControl) && (25 === requestNodeIndex))) { return this._NgControl_25_6; }
    if (((token === import25.NgControlStatus) && (25 === requestNodeIndex))) { return this._NgControlStatus_25_7.context; }
    if (((token === import26.DefaultValueAccessor) && (28 === requestNodeIndex))) { return this._DefaultValueAccessor_28_3.context; }
    if (((token === import27.NG_VALUE_ACCESSOR) && (28 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_28_4; }
    if (((token === import28.NgModel) && (28 === requestNodeIndex))) { return this._NgModel_28_5.context; }
    if (((token === import29.NgControl) && (28 === requestNodeIndex))) { return this._NgControl_28_6; }
    if (((token === import25.NgControlStatus) && (28 === requestNodeIndex))) { return this._NgControlStatus_28_7.context; }
    if (((token === import26.DefaultValueAccessor) && (31 === requestNodeIndex))) { return this._DefaultValueAccessor_31_3.context; }
    if (((token === import27.NG_VALUE_ACCESSOR) && (31 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_31_4; }
    if (((token === import28.NgModel) && (31 === requestNodeIndex))) { return this._NgModel_31_5.context; }
    if (((token === import29.NgControl) && (31 === requestNodeIndex))) { return this._NgControl_31_6; }
    if (((token === import25.NgControlStatus) && (31 === requestNodeIndex))) { return this._NgControlStatus_31_7.context; }
    if (((token === import26.DefaultValueAccessor) && (34 === requestNodeIndex))) { return this._DefaultValueAccessor_34_3.context; }
    if (((token === import27.NG_VALUE_ACCESSOR) && (34 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_34_4; }
    if (((token === import28.NgModel) && (34 === requestNodeIndex))) { return this._NgModel_34_5.context; }
    if (((token === import29.NgControl) && (34 === requestNodeIndex))) { return this._NgControl_34_6; }
    if (((token === import25.NgControlStatus) && (34 === requestNodeIndex))) { return this._NgControlStatus_34_7.context; }
    if (((token === import26.DefaultValueAccessor) && (37 === requestNodeIndex))) { return this._DefaultValueAccessor_37_3.context; }
    if (((token === import27.NG_VALUE_ACCESSOR) && (37 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_37_4; }
    if (((token === import28.NgModel) && (37 === requestNodeIndex))) { return this._NgModel_37_5.context; }
    if (((token === import29.NgControl) && (37 === requestNodeIndex))) { return this._NgControl_37_6; }
    if (((token === import25.NgControlStatus) && (37 === requestNodeIndex))) { return this._NgControlStatus_37_7.context; }
    if (((token === import23.NgForm) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 41)))) { return this._NgForm_19_3.context; }
    if (((token === import24.ControlContainer) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 41)))) { return this._ControlContainer_19_4; }
    if (((token === import25.NgControlStatusGroup) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 41)))) { return this._NgControlStatusGroup_19_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_5_0_0:any = this.context.events;
    this._NgFor_5_6.check_ngForOf(currVal_5_0_0,throwOnChange,false);
    this._NgFor_5_6.ngDoCheck(this,this._anchor_5,throwOnChange);
    this._NgForm_8_3.ngDoCheck(this,this._el_8,throwOnChange);
    this._NgControlStatusGroup_8_5.ngDoCheck(this,this._el_8,throwOnChange);
    this._NgForm_19_3.ngDoCheck(this,this._el_19,throwOnChange);
    this._NgControlStatusGroup_19_5.ngDoCheck(this,this._el_19,throwOnChange);
    this._DefaultValueAccessor_22_3.ngDoCheck(this,this._el_22,throwOnChange);
    const currVal_22_1_0:any = 'name';
    this._NgModel_22_5.check_name(currVal_22_1_0,throwOnChange,false);
    const currVal_22_1_1:any = this.context.eventName;
    this._NgModel_22_5.check_model(currVal_22_1_1,throwOnChange,false);
    this._NgModel_22_5.ngDoCheck(this,this._el_22,throwOnChange);
    this._NgControlStatus_22_7.ngDoCheck(this,this._el_22,throwOnChange);
    this._DefaultValueAccessor_25_3.ngDoCheck(this,this._el_25,throwOnChange);
    const currVal_25_1_0:any = 'description';
    this._NgModel_25_5.check_name(currVal_25_1_0,throwOnChange,false);
    const currVal_25_1_1:any = this.context.description;
    this._NgModel_25_5.check_model(currVal_25_1_1,throwOnChange,false);
    this._NgModel_25_5.ngDoCheck(this,this._el_25,throwOnChange);
    this._NgControlStatus_25_7.ngDoCheck(this,this._el_25,throwOnChange);
    this._DefaultValueAccessor_28_3.ngDoCheck(this,this._el_28,throwOnChange);
    const currVal_28_1_0:any = 'minLat';
    this._NgModel_28_5.check_name(currVal_28_1_0,throwOnChange,false);
    const currVal_28_1_1:any = this.context.minLat;
    this._NgModel_28_5.check_model(currVal_28_1_1,throwOnChange,false);
    this._NgModel_28_5.ngDoCheck(this,this._el_28,throwOnChange);
    this._NgControlStatus_28_7.ngDoCheck(this,this._el_28,throwOnChange);
    this._DefaultValueAccessor_31_3.ngDoCheck(this,this._el_31,throwOnChange);
    const currVal_31_1_0:any = 'minLon';
    this._NgModel_31_5.check_name(currVal_31_1_0,throwOnChange,false);
    const currVal_31_1_1:any = this.context.minLon;
    this._NgModel_31_5.check_model(currVal_31_1_1,throwOnChange,false);
    this._NgModel_31_5.ngDoCheck(this,this._el_31,throwOnChange);
    this._NgControlStatus_31_7.ngDoCheck(this,this._el_31,throwOnChange);
    this._DefaultValueAccessor_34_3.ngDoCheck(this,this._el_34,throwOnChange);
    const currVal_34_1_0:any = 'maxLat';
    this._NgModel_34_5.check_name(currVal_34_1_0,throwOnChange,false);
    const currVal_34_1_1:any = this.context.maxLat;
    this._NgModel_34_5.check_model(currVal_34_1_1,throwOnChange,false);
    this._NgModel_34_5.ngDoCheck(this,this._el_34,throwOnChange);
    this._NgControlStatus_34_7.ngDoCheck(this,this._el_34,throwOnChange);
    this._DefaultValueAccessor_37_3.ngDoCheck(this,this._el_37,throwOnChange);
    const currVal_37_1_0:any = 'maxLon';
    this._NgModel_37_5.check_name(currVal_37_1_0,throwOnChange,false);
    const currVal_37_1_1:any = this.context.maxLon;
    this._NgModel_37_5.check_model(currVal_37_1_1,throwOnChange,false);
    this._NgModel_37_5.ngDoCheck(this,this._el_37,throwOnChange);
    this._NgControlStatus_37_7.ngDoCheck(this,this._el_37,throwOnChange);
    this._vc_5.detectChangesInNestedViews(throwOnChange);
    this._NgControlStatusGroup_8_5.checkHost(this,this,this._el_8,throwOnChange);
    this._NgControlStatusGroup_19_5.checkHost(this,this,this._el_19,throwOnChange);
    this._NgControlStatus_22_7.checkHost(this,this,this._el_22,throwOnChange);
    this._NgControlStatus_25_7.checkHost(this,this,this._el_25,throwOnChange);
    this._NgControlStatus_28_7.checkHost(this,this,this._el_28,throwOnChange);
    this._NgControlStatus_31_7.checkHost(this,this,this._el_31,throwOnChange);
    this._NgControlStatus_34_7.checkHost(this,this,this._el_34,throwOnChange);
    this._NgControlStatus_37_7.checkHost(this,this,this._el_37,throwOnChange);
    const currVal_83:any = this.context.createEventButtonState();
    if (import3.checkBinding(throwOnChange,this._expr_83,currVal_83)) {
      this.renderer.setElementProperty(this._el_39,'disabled',currVal_83);
      this._expr_83 = currVal_83;
    }
  }
  destroyInternal():void {
    this._vc_5.destroyNestedViews();
    this._NgForm_8_3.ngOnDestroy();
    this._NgModel_22_5.ngOnDestroy();
    this._NgModel_25_5.ngOnDestroy();
    this._NgModel_28_5.ngOnDestroy();
    this._NgModel_31_5.ngOnDestroy();
    this._NgModel_34_5.ngOnDestroy();
    this._NgModel_37_5.ngOnDestroy();
    this._NgForm_19_3.ngOnDestroy();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 5)) { return new View_EventComponent1(this.viewUtils,this,5,this._anchor_5,this._vc_5); }
    return (null as any);
  }
  handleEvent_8(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._NgForm_8_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_10(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'change')) {
      const pd_sub_0:any = ((<any>this.context.readUrl($event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_15(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.uploadImage()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_19(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._NgForm_19_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_22(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_22_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.eventName = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_25(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_25_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.description = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_28(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_28_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.minLat = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_31(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_31_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.minLon = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_34(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_34_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.maxLat = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_37(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_37_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.maxLon = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_39(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.createEvent()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}