/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../app/map/leaflet-map.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '@angular/router/src/router';
import * as import9 from '../../../app/event/event.service';
import * as import10 from '../../../app/user/user.service';
import * as import11 from '../../../app/shared/rest.service';
import * as import12 from '../../../app/shared/navigation.service';
import * as import13 from '../../../app/shared/cookie.service';
import * as import14 from '@angular/core/src/zone/ng_zone';
import * as import15 from '@angular/core/src/linker/query_list';
import * as import16 from '../../../app/map/popup.component';
import * as import17 from './popup.component.ngfactory';
import * as import18 from '../../../app/map/marker-menu.component';
import * as import19 from './marker-menu.component.ngfactory';
import * as import20 from '../../../app/map/marker-note.component';
import * as import21 from './marker-note.component.ngfactory';
import * as import22 from '@angular/core/src/linker/element_ref';
export class Wrapper_LeafletMapComponent {
  /*private*/ _eventHandler:Function;
  context:import0.LeafletMapComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any,p4:any,p5:any,p6:any) {
    this._changed = false;
    this.context = new import0.LeafletMapComponent(p0,p1,p2,p3,p4,p5,p6);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_LeafletMapComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_LeafletMapComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.LeafletMapComponent>;
  _LeafletMapComponent_0_3:Wrapper_LeafletMapComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_LeafletMapComponent_Host0,renderType_LeafletMapComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'leaflet-component',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_LeafletMapComponent0(this.viewUtils,this,0,this._el_0);
    this._LeafletMapComponent_0_3 = new Wrapper_LeafletMapComponent(this.injectorGet(import8.Router,this.parentIndex),this.injectorGet(import9.EventService,this.parentIndex),this.injectorGet(import10.UserService,this.parentIndex),this.injectorGet(import11.RestService,this.parentIndex),this.injectorGet(import12.NavigationService,this.parentIndex),this.injectorGet(import13.CookieService,this.parentIndex),this.injectorGet(import14.NgZone,this.parentIndex));
    this.compView_0.create(this._LeafletMapComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._LeafletMapComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.LeafletMapComponent) && (0 === requestNodeIndex))) { return this._LeafletMapComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._LeafletMapComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const LeafletMapComponentNgFactory:import7.ComponentFactory<import0.LeafletMapComponent> = new import7.ComponentFactory<import0.LeafletMapComponent>('leaflet-component',View_LeafletMapComponent_Host0,import0.LeafletMapComponent);
const styles_LeafletMapComponent:any[] = ([] as any[]);
var renderType_LeafletMapComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_LeafletMapComponent,{});
export class View_LeafletMapComponent0 extends import1.AppView<import0.LeafletMapComponent> {
  _viewQuery_PopupComponent_0:import15.QueryList<any>;
  _viewQuery_MarkerMenuComponent_1:import15.QueryList<any>;
  _viewQuery_MarkerNoteComponent_2:import15.QueryList<any>;
  _el_0:any;
  _text_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _el_31:any;
  _el_32:any;
  _text_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _text_37:any;
  _el_38:any;
  compView_38:import1.AppView<import16.PopupComponent>;
  _PopupComponent_38_3:import17.Wrapper_PopupComponent;
  _text_39:any;
  _el_40:any;
  compView_40:import1.AppView<import18.MarkerMenuComponent>;
  _MarkerMenuComponent_40_3:import19.Wrapper_MarkerMenuComponent;
  _text_41:any;
  _el_42:any;
  compView_42:import1.AppView<import20.MarkerNoteComponent>;
  _MarkerNoteComponent_42_3:import21.Wrapper_MarkerNoteComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_LeafletMapComponent0,renderType_LeafletMapComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._viewQuery_PopupComponent_0 = new import15.QueryList<any>();
    this._viewQuery_MarkerMenuComponent_1 = new import15.QueryList<any>();
    this._viewQuery_MarkerNoteComponent_2 = new import15.QueryList<any>();
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','map-context-menu'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n\n',(null as any));
    this._text_2 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_3 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray4(4,'class','map-button-container','style','bottom: 20px; right: 10px;'),(null as any));
    this._text_4 = this.renderer.createText(this._el_3,'\n',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_3,'button',new import3.InlineArray2(2,'class','map-button btn'),(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_5,'img',new import3.InlineArray2(2,'src','/assets/images/marker_walkable.svg'),(null as any));
    this._text_7 = this.renderer.createText(this._el_3,'\n',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_3,'button',new import3.InlineArray2(2,'class','map-button btn'),(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_8,'img',new import3.InlineArray2(2,'src','/assets/images/marker_border.svg'),(null as any));
    this._text_10 = this.renderer.createText(this._el_3,'\n',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_3,'button',new import3.InlineArray2(2,'class','map-button btn'),(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_11,'img',new import3.InlineArray2(2,'src','/assets/images/marker_flood.svg'),(null as any));
    this._text_13 = this.renderer.createText(this._el_3,'\n',(null as any));
    this._text_14 = this.renderer.createText(this._el_3,'\n',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_3,'button',new import3.InlineArray2(2,'class','map-button btn'),(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'\n    ',(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_15,'img',new import3.InlineArray4(4,'src','/assets/images/info.svg','style','width: 100%;'),(null as any));
    this._text_18 = this.renderer.createText(this._el_15,'\n',(null as any));
    this._text_19 = this.renderer.createText(this._el_3,'\n',(null as any));
    this._text_20 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_21 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray4(4,'class','map-button-container','style','bottom: 20px; left: 10px;'),(null as any));
    this._text_22 = this.renderer.createText(this._el_21,'\n',(null as any));
    this._el_23 = import3.createRenderElement(this.renderer,this._el_21,'button',new import3.InlineArray2(2,'class','map-button btn'),(null as any));
    this._text_24 = this.renderer.createText(this._el_23,'\n    ',(null as any));
    this._el_25 = import3.createRenderElement(this.renderer,this._el_23,'span',new import3.InlineArray2(2,'class','glyphicon glyphicon-chevron-left'),(null as any));
    this._text_26 = this.renderer.createText(this._el_23,'\n',(null as any));
    this._text_27 = this.renderer.createText(this._el_21,'\n',(null as any));
    this._text_28 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_29 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray4(4,'class','map-button-container','style','bottom: 12%; right: 10px;'),(null as any));
    this._text_30 = this.renderer.createText(this._el_29,'\n',(null as any));
    this._el_31 = import3.createRenderElement(this.renderer,this._el_29,'button',new import3.InlineArray2(2,'class','map-button btn'),(null as any));
    this._el_32 = import3.createRenderElement(this.renderer,this._el_31,'img',new import3.InlineArray2(2,'src','/assets/images/crosshair.svg'),(null as any));
    this._text_33 = this.renderer.createText(this._el_29,'\n',(null as any));
    this._text_34 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_35 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'id','map'),(null as any));
    this._text_36 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._text_37 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_38 = import3.createRenderElement(this.renderer,parentRenderNode,'popup',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_38 = new import17.View_PopupComponent0(this.viewUtils,this,38,this._el_38);
    this._PopupComponent_38_3 = new import17.Wrapper_PopupComponent(new import22.ElementRef(this._el_38));
    this.compView_38.create(this._PopupComponent_38_3.context);
    this._text_39 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_40 = import3.createRenderElement(this.renderer,parentRenderNode,'marker-menu',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_40 = new import19.View_MarkerMenuComponent0(this.viewUtils,this,40,this._el_40);
    this._MarkerMenuComponent_40_3 = new import19.Wrapper_MarkerMenuComponent();
    this.compView_40.create(this._MarkerMenuComponent_40_3.context);
    this._text_41 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_42 = import3.createRenderElement(this.renderer,parentRenderNode,'marker-note',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_42 = new import21.View_MarkerNoteComponent0(this.viewUtils,this,42,this._el_42);
    this._MarkerNoteComponent_42_3 = new import21.Wrapper_MarkerNoteComponent(this.parentView.injectorGet(import11.RestService,this.parentIndex));
    this.compView_42.create(this._MarkerNoteComponent_42_3.context);
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_5,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_5));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_8,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_8));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_11,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_11));
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_15,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_15));
    var disposable_4:Function = import3.subscribeToRenderElement(this,this._el_23,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_23));
    var disposable_5:Function = import3.subscribeToRenderElement(this,this._el_31,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_31));
    var disposable_6:Function = import3.subscribeToRenderElement(this,this._el_40,new import3.InlineArray2(2,'onMarkerPicked',(null as any)),this.eventHandler(this.handleEvent_40));
    this._MarkerMenuComponent_40_3.subscribe(this,this.eventHandler(this.handleEvent_40),true);
    this._viewQuery_PopupComponent_0.reset([this._PopupComponent_38_3.context]);
    this.context.popup = this._viewQuery_PopupComponent_0.first;
    this._viewQuery_MarkerMenuComponent_1.reset([this._MarkerMenuComponent_40_3.context]);
    this.context.markerMenu = this._viewQuery_MarkerMenuComponent_1.first;
    this._viewQuery_MarkerNoteComponent_2.reset([this._MarkerNoteComponent_42_3.context]);
    this.context.markerNote = this._viewQuery_MarkerNoteComponent_2.first;
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._el_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._el_42
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import16.PopupComponent) && (38 === requestNodeIndex))) { return this._PopupComponent_38_3.context; }
    if (((token === import18.MarkerMenuComponent) && (40 === requestNodeIndex))) { return this._MarkerMenuComponent_40_3.context; }
    if (((token === import20.MarkerNoteComponent) && (42 === requestNodeIndex))) { return this._MarkerNoteComponent_42_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_38_0_0:any = this.context.clickX;
    this._PopupComponent_38_3.check_x(currVal_38_0_0,throwOnChange,false);
    const currVal_38_0_1:any = this.context.clickY;
    this._PopupComponent_38_3.check_y(currVal_38_0_1,throwOnChange,false);
    this._PopupComponent_38_3.ngDoCheck(this,this._el_38,throwOnChange);
    this._MarkerMenuComponent_40_3.ngDoCheck(this,this._el_40,throwOnChange);
    this._MarkerNoteComponent_42_3.ngDoCheck(this,this._el_42,throwOnChange);
    this.compView_38.internalDetectChanges(throwOnChange);
    this.compView_40.internalDetectChanges(throwOnChange);
    this.compView_42.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_38.destroy();
    this.compView_40.destroy();
    this.compView_42.destroy();
    this._MarkerMenuComponent_40_3.ngOnDestroy();
  }
  handleEvent_5(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.primeMarker(this.context.markerTypeRef.WALKABLE)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_8(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.primeMarker(this.context.markerTypeRef.BORDER)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_11(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.primeMarker(this.context.markerTypeRef.FLOOD)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_15(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.toggleInfo()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_23(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.gotoEvents()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_31(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.centerMap()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_40(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'onMarkerPicked')) {
      const pd_sub_0:any = ((<any>this.context.onMarkerPicked($event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}